### ISSUE TITLE
plumber api in webbrowser

### ISSUE THREAD

**Issue by riskcede** [ChrisBeeley/reports_with_plumber#1]
Hi Chris

When i run your example in rstudio it works perfectly, even when i copy the request url from the swagger window to my browser it displays the html output perfectly. But when i call the api directly from the browser it only gives me an error message of Internal error.

Is there any way that i can see a log of this error to find out what is going wrong?

Could it be a rights issue that the rmd file cannot be rendered?

Thanks
Jan

**Comment by ChrisBeeley** [comment]
Sorry about this. RMarkdown was adding a .docx or .html file extension which was messing up the filepath. 

It worked before so I guess it's due to a package update (?)

I've pushed some different code that fixes the error. Annoyingly, the word document comes through with the filename of "word" instead of e.g. "word.docx" but I thought it was better than nothing for now.

I'll try to come back to this in the future for a better fix (HTML works fine AFAIK)
